logging:
  level:
    root: info
    '[org.springframework.orm.jpa]': debug
    '[com.zoostarinc]': debug
    '[net.zoostar]': debug

spring:
  data:
    mongodb:
      uri: mongodb+srv://pratik_db_user:${portfolio.datasource.password}@cluster0.vy1xwq4.mongodb.net/portfolio-dev?appName=Cluster0
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 810043606026-dg6lrjmrf2ie4538tq60tkeq7fiuqqkh.apps.googleusercontent.com
            clientSecret: ${client.secret.portfolio-api.google}
            scope:
              - openid
              - profile
              - email
