base-url:
  portfolio-api: http://localhost:2080/portfolio-api

logging:
  level:
    root: info
    '[com.zoostarinc]': trace
    '[net.zoostar]': trace
    '[org.springframework.web.client]': trace

