build:
  name: '@build.number@'
  version: '@project.version@'
  timestamp: '@build.timestamp@'

logging:
  file:
    name: "logs/@project.build.finalName@.log"
  logback:
    rollingpolicy:
      file-name-pattern: "logs/archive/@project.build.finalName@-%d{yyyy-MM-dd}.%i.log.zip"
      max-history: 10
  
server:
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 2048
  servlet:
    context-path: '/@project.build.finalName@'

spring:
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  output:
    ansi:
      enabled: always
  profiles:
    active:
      - local # default spring boot profile
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 810043606026-uklrbdff94998s1mincvkkl1qpundqtt.apps.googleusercontent.com
            clientSecret: ${client.secret.portfolio-web.google}
            scope:
              - openid
              - profile
              - email
